reproduce cargo bug
In this commit, I've switched some deps from crates.io to git. Note that
the lockfile isn't touched, and still mentions the old deps.

If I run `cargo check`, it fails with a very confusing error message:

```
λ cargo check -p near-sdk-sim
    Updating git repository `https://github.com/near/nearcore.git`
    Updating crates.io index
error: failed to select a version for `wasmer-runtime-core-near`.
    ... required by package `wasmer-runtime-near v0.17.1`
    ... which is depended on by `near-vm-runner v3.0.0 (https://github.com/near/nearcore.git?rev=8a37d39629885a41dde58b60642bcf1e99407d90#8a37d396)`
    ... which is depended on by `node-runtime v3.0.0 (https://github.com/near/nearcore.git?rev=8a37d39629885a41dde58b60642bcf1e99407d90#8a37d396)`
    ... which is depended on by `near-sdk-sim v3.2.0 (/home/matklad/projects/near-sdk-rs/near-sdk-sim)`
versions that meet the requirements `=0.17.1` are: 0.17.1

all possible versions conflict with previously selected packages.

  previously selected package `wasmer-runtime-core-near v0.17.4`
    ... which is depended on by `near-vm-runner v3.0.0 (https://github.com/near/nearcore.git?rev=8a37d39629885a41dde58b60642bcf1e99407d90#8a37d396)`
    ... which is depended on by `node-runtime v3.0.0 (https://github.com/near/nearcore.git?rev=8a37d39629885a41dde58b60642bcf1e99407d90#8a37d396)`
    ... which is depended on by `near-sdk-sim v3.2.0 (/home/matklad/projects/near-sdk-rs/near-sdk-sim)`
```

The culprit here seems to be Cargo.lock -- if I remove it, dependency
resolution works:

```
λ rm Cargo.lock && cargo check -p near-sdk-sim
    Updating crates.io index
    Updating git repository `https://github.com/near/nearcore.git`
    Checking near-sdk-sim v3.2.0 (/home/matklad/projects/near-sdk-rs/near-sdk-sim)
```